name: Docker
on:
  workflow_run:
    workflows: [Build]
    types: [completed]
jobs:
  release-please:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    steps:
      - uses: actions/checkout@v3 
        name: Check out code
      # The logic below handles the docker build and publication:
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: webspaceiq/fedha-v1-core
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

