name: Social Media Notification

on:
  release:
    types:
      - published
      - created

jobs:
  discord_notification:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
      uses: Ilshidur/action-discord@master
      with:
        args: "New release ${{ github.event.release.name }} of ${{ github.repository }} is available. Check it out at ${{ github.event.release.html_url }}"